export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ATTEMPT = "LOGOUT_ATTEMPT";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERROR = 'CLEAR_ERROR';